name: Publish Binary
permissions: write-all

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'preview'

      - name: Build
        run: dotnet build m1pplauncher/m1pplauncher.csproj -r win-x64

      - name: Zip Artifacts
        run: |
          Compress-Archive -Path m1pplauncher/bin/Debug/net10.0-windows10.0.19041.0/win-x64/* -DestinationPath m1pplauncher-artifacts.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: m1pplauncher-artifacts
          path: m1pplauncher-artifacts.zip
