name: Publish Binary
permissions: write-all

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'preview'

      - name: Build
        run: dotnet publish m1pplauncher/m1pplauncher.csproj -c Debug -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:PublishTrimmed=false -o artifacts

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/m1pplauncher.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
