name: Publish Binary
permissions: write-all

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'preview'

      - name: Build
        run: dotnet publish m1pplauncher/m1pplauncher.csproj -c Release -r win-x64 --self-contained false /p:PublishSingleFile=false /p:PublishReadyToRun=false /p:PublishTrimmed=false

      - name: Zip Artifacts
        run: |
          Compress-Archive -Path m1pplauncher/bin/* -DestinationPath m1pplauncher.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: m1pplauncher
          path: m1pplauncher.zip
